apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: tickbook
  labels:
    app: user-service
    app.kubernetes.io/part-of: tickbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/nmdra/tickbook/user-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: tickbook-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: tickbook-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: tickbook-config
                  key: USER_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tickbook-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tickbook-secrets
                  key: DB_PASSWORD
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: tickbook-config
                  key: KAFKA_BROKERS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tickbook-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: tickbook
  labels:
    app: user-service
    app.kubernetes.io/part-of: tickbook
spec:
  selector:
    app: user-service
  ports:
    - port: 3002
      targetPort: 3002
